// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DissapearFooterController from "./dissapear_footer_controller"
application.register("dissapear-footer", DissapearFooterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SelectlocationController from "./selectlocation_controller"
application.register("selectlocation", SelectlocationController)

import SubmitrequestController from "./submitrequest_controller"
application.register("submitrequest", SubmitrequestController)
